### ISSUE TITLE
Scrape other languages?

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/sushi-chef-teachengineering#4]
### Description

Some of the articles and lessons are available in Spanish. Should we extract those as well? If yes, should it be a separate channel TeachEngineering (es)? or part of the en channel?

**Comment by elaeon** [comment]
I think, if we have a channel for each language, in this case TeachEngineering and TeachEngineering(es) is more valuable and the resources are more easy to find for a non english speaker.
